### ISSUE TITLE
[enhancement]캐릭터 보폭 줄이기

### ISSUE THREAD

**Issue by hyunvely** [OS2022project/os_project#5]
if event.key == pygame.K_LEFT:
            person_dx = -1
        elif event.key == pygame.K_RIGHT:
            person_dx = 1

캐릭터 보폭이 너무 작아서 -5,5로 수정이 필요할 것 같습니다.

**Comment by Juyeon823** [comment]
네! 제가 수정하겠습니다. 보폭 늘릴게요!

**Comment by Juyeon823** [comment]
iss5 해결해서 닫겠습니다!
