### ISSUE TITLE
[Invalid] 변수명 수정이 필요합니다.

### ISSUE THREAD

**Issue by choiJY19** [OS2022project/os_project#6]
저희는 호랑이와 마늘 이미지를 사용하니 변수명도 tiger와 garlic으로 수정이 필요해 보입니다.

17번째 줄 - bomb_image : garlic_image
28번째 줄 - person_image : tiger_image
33번째 줄 - person_dx : tiger_dx

이 외에도 person과 bomb가 들어간 부분도 변수명 함께 수정하면 좋을 것 같습니다.

**Comment by hyunvely** [comment]
변수명 제가 수정하겠습니다.

**Comment by Juyeon823** [comment]
제가 대신 수정하겠습니다!

**Comment by Juyeon823** [comment]
완료하여 issue 닫겠습니다.
