### ISSUE TITLE
[bug]캐릭터의 끝값 조정하는 코드 추가 필요

### ISSUE THREAD

**Issue by Juyeon823** [OS2022project/os_project#8]
person.left = person.left + person_dx
로만 되어있는데 이렇게 되면 캐릭터(호랑이)가 만약 좌측이나 우측 끝점에 도달하게 되면 더 이상 이동하지 않습니다. 
초기에 설정한 게임판을 나가 더 이상 캐릭터가 보이지 않기 때문입니다. 따라서  추가적인 코드가 필요해 보입니다.

**Comment by choiJY19** [comment]
제가 해당 코드 수정하겠습니다.

**Comment by Juyeon823** [comment]
병합된거 확인해서 이슈 닫을게요!
